### PR TITLE
Use timezone.now instead of datetime.utcnow

### PR DESCRIPTION
**Pull request by cpolcyn**
Makes the time objects timezone aware

### CODE REVIEW

**Comment by cdcarter** [comment]
which timezone does this use? the timezone of the django user who kicked off the build? the timezone of the build worker task process?

**Comment by cpolcyn** [comment]
It's timezone aware, so under the hood it's always UTC and can be adapted to other timezones as needed based on browser location.

**Comment by cpolcyn** [comment]
timezone.now is used elsewhere in the code so this is really just bringing these stragglers in line.

**Comment by cdcarter** [comment]
ah, timezone *aware* - cool!

**Pull request merged**
